# Generated by Django 2.2.3 on 2019-07-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='end_fiscal_date',
            field=models.CharField(blank=True, max_length=50, verbose_name='End fiscal date'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='enterprise_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Enterprise Status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='enterprise_number',
            field=models.CharField(max_length=12, null=True, verbose_name='Enterprise Number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='enterprise_status',
            field=models.CharField(blank=True, max_length=12, verbose_name='Enterprise Status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='legal_form',
            field=models.CharField(blank=True, max_length=255, verbose_name='Legal form'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='legal_situation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Legal Situation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_address_city',
            field=models.CharField(blank=True, max_length=255, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_address_country',
            field=models.CharField(blank=True, max_length=255, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_address_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_address_street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_address_zip',
            field=models.CharField(blank=True, max_length=20, verbose_name='Zip Code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
