# Generated by Django 2.2.3 on 2019-07-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_auto_20190708_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
