from foo.models import Foo, Bar, Multibar

b1 = Bar(name="Bar1")
b1.save()
b2 = Bar(name="Bar2")
b2.save()
b3 = Bar(name="Bar3")
b3.save()
b4 = Bar(name="Bar4")
b4.save()
b5 = Bar(name="Bar5")
b5.save()
b6 = Bar(name="Bar6")
b6.save()

mb1 = Multibar(name="Multibar1")
mb1.save()
mb2 = Multibar(name="Multibar2")
mb2.save()
mb3 = Multibar(name="Multibar3")
mb3.save()
mb4 = Multibar(name="Multibar4")
mb4.save()

foo1 = Foo(name="Foo1", bar=b1)
foo1.save()
foo1.multibars.add(mb1)
foo1.multibars.add(mb2)
foo1.save()

foo2 = Foo(name="Foo2", bar=b2)
foo2.save()
foo2.multibars.add(mb3)
foo2.multibars.add(mb4)
foo2.save()
