# Generated by Django 2.2.13 on 2020-10-29 14:25

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Street')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Number')),
                ('zipcode', models.CharField(blank=True, max_length=20, verbose_name='Zip Code')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('country', django_countries.fields.CountryField(blank=True, default='BE', max_length=255, verbose_name='Country')),
            ],
        ),
    ]
