# Generated by Django 2.2.3 on 2019-07-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Bar',
            },
        ),
        migrations.CreateModel(
            name='Multibar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Multibar',
            },
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foo.Bar', verbose_name='bar')),
                ('multibars', models.ManyToManyField(blank=True, to='foo.Multibar', verbose_name='multibars')),
            ],
            options={
                'verbose_name': 'Foo',
            },
        ),
    ]
