# Generated by Django 2.2 on 2019-07-31 09:47

from django.db import migrations, models
import django.db.models.deletion
import vies.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(blank=True, max_length=255, verbose_name='Enterprise Name')),
                ('enterprise_number', models.CharField(max_length=30, null=True, validators=[vies.validators.VATINValidator(validate=True, verify=True)], verbose_name='Enterprise Number')),
                ('enterprise_status', models.CharField(blank=True, max_length=12, verbose_name='Enterprise Status')),
                ('legal_situation', models.CharField(blank=True, max_length=50, verbose_name='Legal Situation')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('legal_form', models.CharField(blank=True, max_length=255, verbose_name='Legal form')),
                ('end_fiscal_date', models.CharField(blank=True, max_length=50, verbose_name='End fiscal date')),
                ('social_address_street', models.CharField(blank=True, max_length=255, verbose_name='Street')),
                ('social_address_number', models.CharField(blank=True, max_length=20, verbose_name='Number')),
                ('social_address_zip', models.CharField(blank=True, max_length=20, verbose_name='Zip Code')),
                ('social_address_city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('social_address_country', models.CharField(blank=True, max_length=255, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Company',
            },
        ),
        migrations.CreateModel(
            name='Iban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(blank=True, max_length=20, null=True, verbose_name='IBAN')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'verbose_name': 'Iban',
            },
        ),
    ]
