# Generated by Django 2.2.13 on 2020-10-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0002_auto_20201030_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='proposed_amount',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Mensualité proposée'),
        ),
    ]
