# Generated by Django 2.2.13 on 2020-11-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0003_company_proposed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_proposed_amount',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
