# Generated by Django 2.2.13 on 2020-11-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_date_proposed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
