# Generated by Django 2.2.13 on 2020-11-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[(1, 'subscription'), (2, 'actived subscription'), (3, 'completed folder'), (4, 'final offer sent'), (5, 'accepted folder')], default=1, max_length=50, verbose_name='Status'),
        ),
    ]
