# Generated by Django 2.2.13 on 2020-11-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20201124_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[(1, 'subscription'), (2, 'actived subscription'), (3, 'completed folder'), (4, 'final offer sent'), (5, 'accepted folder'), (6, 'actived')], default=1, max_length=50, verbose_name='Status'),
        ),
    ]
